<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <IsPackable>true</IsPackable>
    <PackageId>TheSingularityWorkshop.MicroBundleRepository.Azure</PackageId>
    <Version>0.1.0-alpha.1</Version>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="....CoreTheSingularityWorkshop.MicroBundleRepository.CoreTheSingularityWorkshop.MicroBundleRepository.Core.csproj" />
    <PackageReference Include="Azure.Identity" Version="1.18.0" />
    <PackageReference Include="Azure.Storage.Blobs" Version="12.29.2" />
  </ItemGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="" />
  </ItemGroup>

</Project>
